apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: aimodel
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata:
  name: aimodel-v-version1
spec:
  rootResource: aimodel
  components:
  - name: aimodel
    type: container
    properties:
      modelFile: "https://raw.githubusercontent.com/msftcoderdjw/eclipse-symphony/refs/heads/users/jesse/aidemo/docs/samples/script-provider/aimodel/iris_model.pkl"