apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: polling-campaign
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: polling-campaign-v-v1
spec:
  rootResource: polling-campaign
  firstStage: "list"
  selfDriving: true
  stages:
    list:
      name: "list"
      provider: "providers.stage.list"     
      inputs:
        objectType: "instance"
      stageSelector: "check"
    check:
      name: "check"
      provider: "providers.stage.script"
      config:
        scriptFolder: "https://raw.githubusercontent.com/msftcoderdjw/eclipse-symphony/configdemo/docs/samples/monitork8s-stage"
        scriptEngine: "bash"
        script: "verify-instance.sh"
      inputs:
        items: "${{$output(list,items)}}"
      stageSelector: ${{$if($equal($output(check,status), 200),'end','list')}}
    end:
      name: "end"
      provider: "providers.stage.mock"      
      stageSelector: ""