apiVersion: workflow.symphony/v1
kind: CampaignContainer
metadata:
  name: staging-campaign
spec:  
---
apiVersion: workflow.symphony/v1
kind: Campaign
metadata:
  name: staging-campaign-v-v1
spec:
  rootResource: staging-campaign
  firstStage: "staging"
  selfDriving: true
  stages:
    staging:
      name: "staging"
      provider: "providers.stage.script"     
      config: 
        scriptFolder: "https://raw.githubusercontent.com/msftcoderdjw/eclipse-symphony/staging/docs/samples/staging"
        scriptEngine: "bash"
        script: "staging.sh"
        # stageSelector: ${{$if($equal($output(approval,status), 200),'deploy','end')}}     
        stageSelector: "end"
    # deploy:
    #   name: "deploy"
    #   provider: "providers.stage.materialize"
    #   inputs:
    #     names:
    #     - "staging-prometheus-instance"
    end:
      name: "end"
      provider: "providers.stage.mock"      
      stageSelector: ""