apiVersion: solution.symphony/v1
kind: SolutionContainer
metadata:
  name: staging-prometheus-server  
spec:
---
apiVersion: solution.symphony/v1
kind: Solution
metadata: 
  name: staging-prometheus-server-v-v1
spec:
  rootResource: staging-prometheus-server
  metadata:
    deployment.replicas: "#1"
    service.ports: "[{\"name\":\"port9090\",\"port\": 9090}]"
    service.type: "LoadBalancer"
  components:
  - name: sample-prometheus-server
    type: container
    properties:
      container.ports: "[{\"containerPort\":9090,\"protocol\":\"TCP\"}]"
      container.imagePullPolicy: "Always"
      container.resources: "{\"requests\":{\"cpu\":\"100m\",\"memory\":\"100Mi\"}}"        
      container.image: "harbor.contoso.com/library/prometheus"