fullnameOverride: symphony
symphonyImage:
  repository: ghcr.io/eclipse-symphony/symphony-k8s
  pullPolicy: IfNotPresent
  tag: "{VERSION}"
paiImage:
  repository: ghcr.io/eclipse-symphony/symphony-api
  pullPolicy: IfNotPresent
  tag: "{VERSION}"
CUSTOM_VISION_KEY: "AAAA"
installServiceExt: true
global:
  azure:
    identity:
      isEnabled: false
observability:
  tracing:
    exporter:
      zipkin: true
  otelCollector:
    enabled: true
    image: otel/opentelemetry-collector:0.103.0
  otelForwarder:
    enabled: true
    image: mcr.microsoft.com/oss/otel/opentelemetry-collector-contrib:0.102.1
zipkin:
  fullnameOverride: symphony-zipkin
cert-manager:
  fullnameOverride: symphony-cert-manager
flavor: oss
redis:
  enabled: true
  asSidecar: false
  image: redis/redis-stack-server:latest
  port: 6379
kubeRbacProxy:
  image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
parent:
  url:
  username: admin
  password:
siteId: hq
api:
  apiContainerPortHttp: 8080
  apiContainerPortHttps: 8081
  labelKey:
  labelValue:
  annotationKey: 
symphony:
  incluster:
    httpsport: 8081
    httpport: 8080
  extension:
    httpsport: 8081
    httpport: 8080
Azure:
  proxySettings:
    isProxyEnabled: false
    httpProxy: ""
    httpsProxy: ""
    noProxy: ""
    proxyCert: ""
  Extension:
    ResourceId: "/subscriptions/af54d2ce-0dcb-48f8-9d2d-ff9c53e48c8d/resourcegroups/jiadutestaks0618c_group/providers/Microsoft.Kubernetes/ConnectedClusters/jiadutestaks0618c/providers/Microsoft.KubernetesConfiguration/extensions/symphonyext"
  Cluster:
    Region: "eastus"
    ResourceId: "/subscriptions/af54d2ce-0dcb-48f8-9d2d-ff9c53e48c8d/resourcegroups/jiadutestaks0618c_group/providers/Microsoft.Kubernetes/connectedClusters/jiadutestaks0618c"
otlpLogsEndpointGrpc: symphony-otel-collector-service.default.svc:4317
otlpMetricsEndpointGrpc: symphony-otel-collector-service.default.svc:4317
otlpInsecureGrpc: true